# See config.example.yml for documentation.
object_base: orig/GKYE
object: sys/main.dol
hash: 977533bb96e6a16e127946396489be1b4164ac42
symbols: config/GKYE/symbols.txt
splits: config/GKYE/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
